title : 谢特
tagline: Blog Tagline
author :
  name : 谢特
  email : hi.nareix@gmail.com
  github : nareix
  twitter : nareix
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
