title : 制造糯米
tagline: Blog Tagline
author :
  name : nareix
  email : 0@fill0.com
  github : nareix
  twitter : nareix
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
