title : nareix
tagline: Blog Tagline
author :
  name : nareix
  email : hi.nareix@gmail.com
  github : nareix
  twitter : nareix
  feedburner : feedname

navigation :
  - projects.html
  - archive.html
  - tags.html
  - about.md
  
