title : nareix's Blog
tagline: Blog Tagline
author :
  name : nareix
  email : hi.nareix@gmail.com
  github : nareix
  twitter : nareix
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
